{
    "name": "v__cloud_instances_manager",
    "version": "16.0.1.0.0",
    "description": "management of cloud instances of all our clients",
    "summary": "Create a module named “v__cloud_instances_manager”",
    "category": "External",
    "author": "VEGANET",
    "website": "https://www.vegagroup.com.tn",
    "license": "Other proprietary",
    "depends": ["base", "hr", "project", "web", "base_automation"],
    "data": [
        "views/cloud_instances_views.xml",
        "security/ir.model.access.csv",
        "views/menu_views.xml",
        "views/hosting_provider_views.xml",
        "views/odoo_version_views.xml",
        "views/operating_system_views.xml",
        "views/vpn_type_views.xml",
        "views/project_project_views.xml",
        "data/cloud_instance_data.xml",
        "security/cloud_instance_security.xml",
        "data/mail_template_data.xml"
    ],
    "application": False,
    "auto_install": False,
    "installable": True,
    "images": ["static/description/icon.png"],
    "sequence": 1,
}
